config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/about',    to: 'static_pages#about'
  get  '/signup',   to: 'users#new'

  resources :tasks
  resources :users do
    resources :tasks
  end

  resources :projects do
    resources :tasks
  end
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :project
  belongs_to :user

  validates :title,       presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :project_id,     presence: true

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  # before_action :logged_in_user,      only: [:index]
  # before_action :correct_task_user,   only: [:update]
  before_action   :admin_user,          only: [:destroy]

  def index
    if admin?
      @tasks = Task.paginate(page: params[:page])
    else
      @user_name = full_name(current_user)
      @tasks = current_user.tasks.paginate(page: params[:page])
    end

  end

  def show
    @task = Task.find(params[:id])
    @user = User.find_by(id: @task.user_id)
  end

  def new
    @task = Task.new
    @users = User.all_except_admin
  end

  def edit
    @task = Task.find(params[:id])
    # @user = User.find_by(id: @task.user_id)
    @users = User.all_except_admin
  end

  def create
    @project = Project.find(params[:task][:project_id])
    @task = @project.tasks.build(task_params)
    if @task.save
      flash[:success] = "Task '#{@task.title}' created!"
      redirect_back_or @project
    else
      render 'new'
    end
  end

  def update
    @users = User.all_except_admin
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Task '#{@task.title}' updated"
      redirect_to admin? ? tasks_url : edit_user_url
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    Task.find(params[:id]).destroy
    flash[:success] = "Task '#{@task.title}' deleted"
    redirect_to tasks_url
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :status, :user_id, :project_id)
  end

  # Confirms the correct user.
  def correct_task_user
    @user = User.find(session[:user_id])
    @task = Task.find(params[:id])
    redirect_to(root_url) unless @user.tasks.find_by(id: @task.id)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

  def get_statuses
     [
        'NEW',
        'IN PROGRESS',
        'DONE'
    ]
  end

  def get_users(users)
    users.collect{|u| [full_name(u), u.id]}
  end

end

app/views/tasks/_task.html.erb
<tr>
  <th>
    <%= link_to task.title, task%>
  </th>
  <th colspan="2">
    <%= task.description %>
  </th>
  <th>
    <%= task.status %>
  </th>
  <th >
    <% if executor?(task) || admin? %>
    <%= link_to "update", edit_task_path(task.id), class: 'btn btn-warning' %>
    <% end %>
  </th>

  <th>
    <% if current_user.admin? %>
      <button type="button" class="btn btn-danger"
              data-toggle="modal" data-target="#deleteModal<%= task.id %>">
        delete
      </button>
    <% end %>
  </th>
</tr>


<div class="modal fade" id="deleteModal<%= task.id %>" tabindex="-1" role="dialog"
     aria-labelledby="deleteModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title center" id="exampleModalLabel">Delete '<%= task.title %>'</h4>
        <button class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body center">
        <h3>Are you sure?</h3>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">
          Cancel
        </button>
        <%= link_to 'Delete', task, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Update task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :status %>
        <%= f.select :status, get_statuses, {}, class: 'form-control' %>
      </div>

      <div>
        <%= f.label "Executor" %>
        <%= f.select :user_id, get_users(@users), {}, class: 'form-control' %>
      </div>

      <div>
        <div id="submit">
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>

        <div id="cancel">
          <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<% if admin? %>
  <h1>Tasks</h1>
<% else %>
  <h1><%= @user_name %> tasks</h1>
<% end %>

<%= will_paginate %>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="colgroup" colspan="2">Description</th>
    <th scope="col">Status</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody class="tasks">
    <% @tasks.each do |task| %>
      <%= render task %>
    <% end %>
  </tbody>
</table>


app/views/tasks/new.html.erb
<h2>New task</h2>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= form_for(@task) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.hidden_field :project_id, value: params[:project_id] %>

      <div>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div>
        <%= f.label "Executor" %>
        <%= f.select :user_id, get_users(@users), {}, class: 'form-control' %>
      </div>

      <div id="task-form-footer">
        <div id="submit">
          <%= f.submit "Submit", class: "btn btn-success" %>
        </div>

        <div id="cancel">
          <%= link_to "Cancel", :back %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<table id="show-task" class="table">
  <tbody class="tasks">
    <tr>
      <th scope="colgroup" colspan="3">Title</th>
      <th scope="colgroup" colspan="9">
        <%= @task.title %>
      </th>
    </tr>

    <tr>
      <th scope="colgroup" colspan="3">Description</th>
      <th scope="colgroup" colspan="9">
        <%= @task.description %>
      </th>
    </tr>

    <tr>
      <th scope="colgroup" colspan="3">Status</th>
      <th scope="colgroup" colspan="9">
        <%= @task.status %>
      </th>
    </tr>

    <tr>
      <th scope="colgroup" colspan="3">Executor</th>
      <th scope="colgroup" colspan="9">
        <%= @user.first_name %> <%= @user.last_name %>
      </th>
    </tr>

    <tr>
      <th scope="colgroup" colspan="12">
        <%= link_to "Back", :back %>
      </th>
    </tr>
  </tbody>
</table>
