config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/about',    to: 'static_pages#about'
  get  '/signup',   to: 'users#new'

  resources :tasks
  resources :users do
    resources :tasks
  end

  resources :projects do
    resources :tasks
  end
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :tasks, dependent: :destroy
  self.per_page = 10

  validates :name,       presence: true, length: { maximum: 100}
  validates :summary,    presence: true, length: { maximum: 1000}
  validates :start_date, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :logged_in_user,   only: [:index]
  # before_action :check_for_cancel, only: [:create, :update]

  def index
    @projects = Project.order(start_date: :desc).paginate(:page => params[:page])
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    project_name = params[:project][:name]
    if @project.save
      flash[:success] = "Project '#{project_name}' successfully created!"
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      flash[:success] = "Project '#{@project.name}' updated"
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    Project.find(params[:id]).destroy
    flash[:success] = "Project #{@project.name} deleted"
    redirect_to projects_url
  end

  private
  def project_params
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def current_project?(project)
    project == current_project
  end

  def date_time_format?
    "%d/%m/%Y %H:%M"
  end

  def check_end_date(datetime)
    datetime.strftime(date_time_format?) unless datetime.nil?
    (DateTime.now + 1.year).strftime(date_time_format?)
  end

end

app/views/projects/_project.html.erb
<tr>
  <th>
    <%= link_to project.name, project %>
  </th>
  <th colspan="2">
    <%= project.summary %>
  </th>
  <th>
    <%= project.start_date.strftime(date_time_format?) %>
  </th>
  <th>
    <%= check_end_date(project.end_date)%>
  </th>

  <% if current_user.admin? %>
    <th >
      <%= link_to "update", edit_project_path(project), class: 'btn btn-warning' %>
    </th>

    <th>
      <%#= render partial: "shared/_delete-modal.html.erb" %>
      <button type="button" class="btn btn-danger"
              data-toggle="modal" data-target="#deleteModal<%= project.id %>">
        Delete
      </button>

    </th>
  <% end %>
</tr>

<div class="modal fade" id="deleteModal<%= project.id %>" tabindex="-1" role="dialog"
     aria-labelledby="deleteModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
        <button class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        Are you sure?
      </div>

      <!-- Delete button in the footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">
          Cancel
        </button>
        <%= link_to 'Delete', project, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update project</h1>

<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= form_for(@project) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :summary %>
        <%= f.text_area :summary, class: 'form-control' %>
      </div>

      <div>
        <div id="start-date">
          <%= f.label :start_date %>
          <%= f.date_field :start_date, class: 'form-control' %>
        </div>
        <div id="start-time">
          <%= "Start time" %>
          <%= f.time_field :start_date, ignore_date: true, class: 'form-control' %>
        </div>
      </div>

      <div>
        <div id="end-date">
          <%= f.label :end_date %>
          <%= f.date_field :end_date, class: 'form-control' %>
        </div>
        <div id="end-time">
          <%= "End time" %>
          <%= f.time_field :end_date, ignore_date: true, class: 'form-control' %>
        </div>
      </div>

      <%= link_to 'Add new task', new_project_task_path(@project.id), class: "btn btn-primary"%>

      <div id="form-footer">
        <div id="submit">
          <%= f.submit "Save", class: "btn btn-success" %>
        </div>
        <div id="cancel">
          <%= link_to "Cancel", :back, class: "btn btn-light" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<h1>All projects</h1>

<% if admin? %>
  <%= link_to "New Project", new_project_path, class: "btn btn-primary" %>
<% end %>

<br>
<%= will_paginate %>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="colgroup" colspan="2">Summary</th>
    <th scope="col">Start date</th>
    <th scope="col">End date</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody class="projects">
  <% @projects.each do |project| %>
    <%= render project %>
  <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>Add new project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div>
        <%= f.label :summary %>
        <%= f.text_field :summary, class: 'form-control' %>
      </div>

      <div>
        <div id="start-date">
          <%= f.label :start_date %>
          <%= f.date_field :start_date, class: 'form-control' %>
        </div>
        <div id="start-time">
          <%= "Start time" %>
          <%= f.time_field :start_date, ignore_date: true, class: 'form-control' %>
        </div>
      </div>

      <div>
        <div id="end-date">
          <%= f.label :end_date %>
          <%= f.date_field :end_date, class: 'form-control' %>
        </div>
        <div id="end-time">
          <%= "End time" %>
          <%= f.time_field :end_date, ignore_date: true, class: 'form-control' %>
        </div>
      </div>

      <div>
        <div id="submit">
          <%= f.submit "Save", class: "btn btn-success" %>
        </div>
        <div id="cancel">
          <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<table id="project-info" class="table">
  <caption class="center">
    <h2>Project Info</h2>
  </caption>
  <tbody class="projects">
  <tr>
    <th scope="colgroup" colspan="3">Name</th>
    <th scope="colgroup" colspan="9">
      <%= @project.name %>
    </th>
  </tr>
  <tr>
    <th scope="colgroup" colspan="3">Summary</th>
    <th scope="colgroup" colspan="9">
      <%= @project.summary %>
    </th>
  </tr>
  <tr>
    <th scope="colgroup" colspan="3">Start date and time</th>
    <th scope="colgroup" colspan="9">
      <% unless @project.start_date.nil? %>
        <%= @project.start_date.strftime("%d/%m/%Y %H:%M") %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th scope="colgroup" colspan="3">End date and time</th>
    <th scope="colgroup" colspan="9">
      <% unless @project.end_date.nil? %>
        <%= @project.end_date.strftime("%d/%m/%Y %H:%M") %>
      <% end %>
    </th>
  </tr>
  </tbody>
</table>

<div id="cancel">
  <%= link_to "Back", projects_path, class: "btn btn-secondary" %>
</div>

<% if @project.tasks.any? %>
  <table id="project-tasks" class="container table">
    <caption class="center">
      <h3>Project Tasks</h3>
    </caption>
    <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="colgroup" colspan="2">Description</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody class="tasks">
    <% @project.tasks.each do |task| %>
      <%= render 'tasks/task', {task: task} %>
    <% end %>
    </tbody>
  </table>
<% end %>