config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get  '/about',    to: 'static_pages#about'
  get  '/signup',   to: 'users#new'

  resources :tasks
  resources :users do
    resources :tasks
  end

  resources :projects do
    resources :tasks
  end
end

app/views/layouts/_footer.html.erb
<footer class="container bg-dark ">
  <div class="m-auto">
    <a href="https://pacific-earth-58270.herokuapp.com//">Project Manager</a>
    by <a href="https://github.com/AliakseiShvants/">Aliaksei Shvants</a>
    <%= link_to "About", about_path, id: "about" %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav id="header" class=" container navbar bg-light">
  <div class="navbar-brand">
    <%= link_to "Project Manager", root_path, id: "logo" %>
  </div>
  <ul class="nav navbar-nav navbar-right" id="menu">
    <li><%= link_to "Home",   root_path %></li>

    <% if logged_in? %>
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "Tasks",    tasks_path %></li>

      <% if current_user.admin? %>
        <li><%= link_to "Users",  users_path %></li>
      <% end %>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
<!--          TODO center logo -->
          <%= gravatar_for current_user, size: 35 %>
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li class="center">Signed in as <br>
            <strong><%= full_name(current_user) %></strong>
          </li>
          <li class="divider"></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "My tasks", user_tasks_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: :delete %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Log in", login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <div class="content container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>
          </div>
        <% end %>
        <%= yield %>
    </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>